name: Publish Package

on:
  push:
    branches:
      - master
      - npm

jobs:
  publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@westdeutscherrundfunkkoeln'
          always-auth: true
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - run: rm -rf example
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn typescript
      - run: yarn version --patch
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
